### ISSUE TITLE
One Hundred Hats

### ISSUE THREAD

**Issue by Siekwiee** [DynamicExtend/Math-Riddles#1]
A prison guard tells his 100 prisoners that they will be playing the following game. The guard will line
up the prisoners single-file, all facing the front of the line. The guard will place a red or a black hat on each
prisoner’s head. There could be any combination of red and black hats (perhaps 50 and 50, perhaps 99 and 1,
perhaps 100 and 0, etc.) and the hats could be in any order. Each prisoner can only see the hats of those in
front of him in line, and not his own hat or those hats behind him. The guard will start with the prisoner at
the end of the line (who can see all hats except his own), and ask “Is your hat red or black?”. If the prisoner
responds correctly, he will be set free. Otherwise he will remain in jail. The guard will then ask the second
to last prisoner in line the same question, with the same consequences. The guard will keep moving forward,
asking the same question, until all 100 prisoners have been asked. Before the guard begins the game, the
prisoners are allowed to devise a strategy. Once the game begins, the prisoners cannot communicate, except
by answering “red” or “black” in response to the guard. They can’t use volume, intonation, or pauses in
their response to communicate, as the guard will notice all these tricks (it’s a math riddle). Your task is to
devise a strategy so that at most one prisoner remains in jail, and so that at least 99 prisoners are set free.
How do you do it?

**Comment by Jendrik0** [comment]
Test

**Comment by Jendrik0** [comment]
Dasijeifmdkf

**Comment by Siekwiee** [comment]
zwr
